apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-168727730
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-168727730
    app.kubernetes.io/part-of: test-app-168727730
  name: java-quarkus-168727730
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-168727730
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-168727730
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/lui-alt-tenant/test-app-168727730/java-quarkus-168727730@sha256:7fdd8e9992831a484a5dec244adb6222e381b967750857a95803ad60758394d1
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
