apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-168727730
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-168727730
    app.kubernetes.io/part-of: test-app-168727730
  name: java-quarkus-168727730
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-168727730
status:
  loadBalancer: {}
